id: app
title: MOU
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-53-r4-ssp
- govready.com/apps/compliance/2017/mou
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST 800-53r4) Compliance of MOU
    long: Generates compliance documentation of MOU as it pertains to managing the
      security of CUI (Controlled Unclassified Information) as per NIST 800-53r4 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    A MOU is a Memorandum of Understanding describing agreend responsibilities between
    two parties.

    This application will make sure you are properly using MOU to protect CUI (Controlled
    Unclassified Information) as per NIST 800-53r4 controls.
questions:
- id: example
  title: Example Module
  type: module
  module-id: example
output:
- id: ssp_nist80053r4_PM_8
  title: NIST 800-53r4 PM-8 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses MOU to the organization addresses information security issues
    in the development, documentation, and updating of a critical infrastructure and
    key resources protection plan. A MOU is a Memorandum of Understanding describing
    agreend responsibilities between two parties.

