id: app
title: Virtual Private Networking (VPN)
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-53-r4-ssp
- govready.com/apps/compliance/2017/virtual-private-networking-(vpn)
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST 800-53r4) Compliance of Virtual Private Networking (VPN)
    long: Generates compliance documentation of Virtual Private Networking (VPN) as
      it pertains to managing the security of CUI (Controlled Unclassified Information)
      as per NIST 800-53r4 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    Virtual Private Network extends a private network across a public network (Wikipedia).

    This application will make sure you are properly using Virtual Private Networking
    (VPN) to protect CUI (Controlled Unclassified Information) as per NIST 800-53r4
    controls.
questions:
- id: example
  title: Example Module
  type: module
  module-id: example
output:
- id: ssp_nist80053r4_AC_17
  title: NIST 800-53r4 AC-17 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Virtual Private Networking (VPN) to the organization:

    a. Establishes and documents usage restrictions, configuration/connection requirements,
    and implementation guidance for each type of remote access allowed; and

    b. Authorizes remote access to the information system prior to allowing such connections.
    Virtual Private Network extends a private network across a public network (Wikipedia).

