id: app
title: Network intrusion detection system
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-53-r4-ssp
- govready.com/apps/compliance/2017/network-intrusion-detection-system
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST 800-53r4) Compliance of Network intrusion detection system
    long: Generates compliance documentation of Network intrusion detection system
      as it pertains to managing the security of CUI (Controlled Unclassified Information)
      as per NIST 800-53r4 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    Network Intrusioin Detection System prevents and detects unauthorized access and
    usage of a computer network.

    This application will make sure you are properly using Network intrusion detection
    system to protect CUI (Controlled Unclassified Information) as per NIST 800-53r4
    controls.
questions:
- id: example
  title: Example Module
  type: module
  module-id: example
output:
- id: ssp_nist80053r4_IR_5
  title: NIST 800-53r4 IR-5 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Network intrusion detection system to the organization tracks
    and documents information system security incidents. Network Intrusioin Detection
    System prevents and detects unauthorized access and usage of a computer network.

