id: app
title: Standard Position Description (SPD)
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-53-r4-ssp
- govready.com/apps/compliance/2017/standard-position-description-(spd)
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST 800-53r4) Compliance of Standard Position Description (SPD)
    long: Generates compliance documentation of Standard Position Description (SPD)
      as it pertains to managing the security of CUI (Controlled Unclassified Information)
      as per NIST 800-53r4 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    Standard Position Description describes the activities and responsibilities of
    organization roles at the Department.

    This application will make sure you are properly using Standard Position Description
    (SPD) to protect CUI (Controlled Unclassified Information) as per NIST 800-53r4
    controls.
questions:
- id: example
  title: Example Module
  type: module
  module-id: example
output:
- id: ssp_nist80053r4_PS_2
  title: NIST 800-53r4 PS-2 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Standard Position Description (SPD) to the organization:

    a. Assigns a risk designation to all organizational positions;

    b. Establishes screening criteria for individuals filling those positions; and

    c. Reviews and updates position risk designations [Assignment: organization-defined
    frequency]. Standard Position Description describes the activities and responsibilities
    of organization roles at the Department.

