id: app
title: Configuration against Denial of Service (DoS) Attacks
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-53-r4-ssp
- govready.com/apps/compliance/2017/configuration-against-denial-of-service-(dos)-attacks
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST 800-53r4) Compliance of Configuration against Denial of Service
      (DoS) Attacks
    long: Generates compliance documentation of Configuration against Denial of Service
      (DoS) Attacks as it pertains to managing the security of CUI (Controlled Unclassified
      Information) as per NIST 800-53r4 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    Configuration against Denial of Service (DoS) Attacks are measures taken to minimize
    threats to the availability of an online information service due to extreme spikes
    in requests for service.

    This application will make sure you are properly using Configuration against Denial
    of Service (DoS) Attacks to protect CUI (Controlled Unclassified Information)
    as per NIST 800-53r4 controls.
questions:
- id: example
  title: Example Module
  type: module
  module-id: example
output:
- id: ssp_nist80053r4_SC_5
  title: NIST 800-53r4 SC-5 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Configuration against Denial of Service (DoS) Attacks to
    the information system protects against or limits the effects of the following
    types of denial of service attacks: [Assignment: organization-defined types of
    denial of service attacks or references to sources for such information] by employing
    [Assignment: organization-defined security safeguards]. Configuration against
    Denial of Service (DoS) Attacks are measures taken to minimize threats to the
    availability of an online information service due to extreme spikes in requests
    for service.

