id: app
title: Unique TACR System user-IDs
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-53-r4-ssp
- govready.com/apps/compliance/2017/unique-lincs-technology-project-user-ids
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST 800-53r4) Compliance of Unique TACR System user-IDs
    long: Generates compliance documentation of Unique TACR System user-IDs
      as it pertains to managing the security of CUI (Controlled Unclassified Information)
      as per NIST 800-53r4 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    Unique TACR System user-IDs are unique identifiers assigned to individuals
    users of TACR with accounts.

    This application will make sure you are properly using Unique TACR Technology
    Project user-IDs to protect CUI (Controlled Unclassified Information) as per NIST
    800-53r4 controls.
questions:
- id: example
  title: Example Module
  type: module
  module-id: example
output:
- id: ssp_nist80053r4_IA_4
  title: NIST 800-53r4 IA-4 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Unique TACR System user-IDs to the organization
    manages information system identifiers by:

    a. Receiving authorization from [Assignment: organization-defined personnel or
    roles] to assign an individual, group, role, or device identifier;

    b. Selecting an identifier that identifies an individual, group, role, or device;

    c. Assigning the identifier to the intended individual, group, role, or device;

    d. Preventing reuse of identifiers for [Assignment: organization-defined time
    period]; and

    e. Disabling the identifier after [Assignment: organization-defined time period
    of inactivity]. Unique TACR System user-IDs are unique identifiers
    assigned to individuals users of TACR with accounts.

