id: app
title: RHEL6
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-53-r4-ssp
- govready.com/apps/compliance/2017/rhel6
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST 800-53r4) Compliance of RHEL6
    long: Generates compliance documentation of RHEL6 as it pertains to managing the
      security of CUI (Controlled Unclassified Information) as per NIST 800-53r4 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    RHEL6 is an enterprise class operating system.

    This application will make sure you are properly using RHEL6 to protect CUI (Controlled
    Unclassified Information) as per NIST 800-53r4 controls.
questions:
- id: example
  title: Example Module
  type: module
  module-id: example
output:
- id: ssp_nist80053r4_SC_39
  title: NIST 800-53r4 SC-39 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses RHEL6 to the information system maintains a separate execution domain for each executing process. RHEL6 is an enterprise class operating system.

