id: app
title: Incident Response Policy
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-53-r4-ssp
- govready.com/apps/compliance/2017/incident-response-policy
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST 800-53r4) Compliance of Incident Response Policy
    long: Generates compliance documentation of Incident Response Policy as it pertains
      to managing the security of CUI (Controlled Unclassified Information) as per
      NIST 800-53r4 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    The Incident Response Policy sets forth and documents the policies and proceedures
    of the Department for responding to adverse performance events impacting information
    systems.

    This application will make sure you are properly using Incident Response Policy
    to protect CUI (Controlled Unclassified Information) as per NIST 800-53r4 controls.
questions:
- id: example
  title: Example Module
  type: module
  module-id: example
output:
- id: ssp_nist80053r4_IR_1
  title: NIST 800-53r4 IR-1 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Incident Response Policy to the organization:

    a. Develops, documents, and disseminates to [Assignment: organization-defined
    personnel or roles]:

    a.1. An incident response policy that addresses purpose, scope, roles, responsibilities,
    management commitment, coordination among organizational entities, and compliance;
    and

    a.2. Procedures to facilitate the implementation of the incident response policy
    and associated incident response controls; and

    b. Reviews and updates the current:

    b.1. Incident response policy [Assignment: organization-defined frequency]; and

    b.2. Incident response procedures [Assignment: organization-defined frequency].
    The Incident Response Policy sets forth and documents the policies and proceedures
    of the Department for responding to adverse performance events impacting information
    systems.

