id: app
title: Department of Sobriety Handbook for Software Management and Acquisition Policy
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-53-r4-ssp
- govready.com/apps/compliance/2017/department-of-education-handbook-for-software-management-and-acquisition-policy
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST 800-53r4) Compliance of Department of Sobriety Handbook for
      Software Management and Acquisition Policy
    long: Generates compliance documentation of Department of Sobriety Handbook for
      Software Management and Acquisition Policy as it pertains to managing the security
      of CUI (Controlled Unclassified Information) as per NIST 800-53r4 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    Department of Sobriety Handbook for Software Management and Acquisition Policy
    sets forth and documents standards and proceedures for the purchase and management
    of software by the Department.

    This application will make sure you are properly using Department of Sobriety
    Handbook for Software Management and Acquisition Policy to protect CUI (Controlled
    Unclassified Information) as per NIST 800-53r4 controls.
questions:
- id: example
  title: Example Module
  type: module
  module-id: example
output:
- id: ssp_nist80053r4_SA_1
  title: NIST 800-53r4 SA-1 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Department of Sobriety Handbook for Software Management
    and Acquisition Policy to the organization:

    a. Develops, documents, and disseminates to [Assignment: organization-defined
    personnel or roles]:

    a.1. A system and services acquisition policy that addresses purpose, scope, roles,
    responsibilities, management commitment, coordination among organizational entities,
    and compliance; and

    a.2. Procedures to facilitate the implementation of the system and services acquisition
    policy and associated system and services acquisition controls; and

    b. Reviews and updates the current:

    b.1. System and services acquisition policy [Assignment: organization-defined
    frequency]; and

    b.2. System and services acquisition procedures [Assignment: organization-defined
    frequency]. Department of Sobriety Handbook for Software Management and Acquisition
    Policy sets forth and documents standards and proceedures for the purchase and
    management of software by the Department.

