id: app
title: Ed Information System Architecture
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-53-r4-ssp
- govready.com/apps/compliance/2017/ed-information-system-architecture
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST 800-53r4) Compliance of Ed Information System Architecture
    long: Generates compliance documentation of Ed Information System Architecture
      as it pertains to managing the security of CUI (Controlled Unclassified Information)
      as per NIST 800-53r4 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    Department of Sobriety System Architecture describes the structure and relationships
    of an organization's business unites, processes, roles, and information systems
    for the Department.

    This application will make sure you are properly using Ed Information System Architecture
    to protect CUI (Controlled Unclassified Information) as per NIST 800-53r4 controls.
questions:
- id: example
  title: Example Module
  type: module
  module-id: example
output:
- id: ssp_nist80053r4_CM_2
  title: NIST 800-53r4 CM-2 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Ed Information System Architecture to the organization develops,
    documents, and maintains under configuration control, a current baseline configuration
    of the information system. Department of Sobriety System Architecture describes
    the structure and relationships of an organization's business unites, processes,
    roles, and information systems for the Department.

