id: app
title: ContractorCo
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-53-r4-ssp
- govready.com/apps/compliance/2017/ContractorCo
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST 800-53r4) Compliance of ContractorCo
    long: Generates compliance documentation of ContractorCo as it pertains to managing
      the security of CUI (Controlled Unclassified Information) as per NIST 800-53r4
      controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    ContractorCo is a Department of Sobriety contractor.

    This application will make sure you are properly using ContractorCo to protect
    CUI (Controlled Unclassified Information) as per NIST 800-53r4 controls.
questions:
- id: example
  title: Example Module
  type: module
  module-id: example
output:
- id: ssp_nist80053r4_MA_5
  title: NIST 800-53r4 MA-5 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses ContractorCo to the organization:

    a. Establishes a process for maintenance personnel authorization and maintains
    a list of authorized maintenance organizations or personnel;

    b. Ensures that non-escorted personnel performing maintenance on the information
    system have required access authorizations; and

    c. Designates organizational personnel with required access authorizations and
    technical competence to supervise the maintenance activities of personnel who
    do not possess the required access authorizations. ContractorCo is a Department
    of Education contractor.

