id: app
title: TACR System Configuration Management Plan (CMP)
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-53-r4-ssp
- govready.com/apps/compliance/2017/tacr-technology-project-configuration-management-plan-(cmp)
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST 800-53r4) Compliance of TACR System Configuration
      Management Plan (CMP)
    long: Generates compliance documentation of TACR System Configuration
      Management Plan (CMP) as it pertains to managing the security of CUI (Controlled
      Unclassified Information) as per NIST 800-53r4 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    TACR System Configuration Management Plan (CMP) sets forth and documents
    how configuration of the TACR baselines and systems are managed.

    This application will make sure you are properly using TACR System
    Configuration Management Plan (CMP) to protect CUI (Controlled Unclassified Information)
    as per NIST 800-53r4 controls.
questions:
- id: example
  title: Example Module
  type: module
  module-id: example
output:
- id: ssp_nist80053r4_CM_1
  title: NIST 800-53r4 CM-1 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses TACR System Configuration Management Plan (CMP)
    to the organization:

    a. Develops, documents, and disseminates to [Assignment: organization-defined
    personnel or roles]:

    a.1. A configuration management policy that addresses purpose, scope, roles, responsibilities,
    management commitment, coordination among organizational entities, and compliance;
    and

    a.2. Procedures to facilitate the implementation of the configuration management
    policy and associated configuration management controls; and

    b. Reviews and updates the current:

    b.1. Configuration management policy [Assignment: organization-defined frequency];
    and

    b.2. Configuration management procedures [Assignment: organization-defined frequency].
    TACR System Configuration Management Plan (CMP) sets forth and documents
    how configuration of the TACR baselines and systems are managed.

- id: ssp_nist80053r4_CM_2
  title: NIST 800-53r4 CM-2 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses TACR System Configuration Management Plan (CMP)
    to the organization develops, documents, and maintains under configuration control,
    a current baseline configuration of the information system. TACR System
    Configuration Management Plan (CMP) sets forth and documents how configuration
    of the TACR baselines and systems are managed.

