id: app
title: Technical Staff
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-53-r4-ssp
- govready.com/apps/compliance/2017/technical-staff
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: draft
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST 800-53r4) Compliance of Technical Staff
    long: Generates compliance documentation of Technical Staff as it pertains to
      managing the security of CUI (Controlled Unclassified Information) as per NIST
      800-53r4 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    The Technical Staff are individuals with responsibility for managing the technical
    aspects of the information system.

    This application will make sure you are properly using Technical Staff to protect
    CUI (Controlled Unclassified Information) as per NIST 800-53r4 controls.
questions:
- id: example
  title: Example Module
  type: module
  module-id: example
output:
- id: ssp_nist80053r4_AC_3
  title: NIST 800-53r4 AC-1 Control Implementation
  format: markdown
  template: >+
    The technical support staff ensures that access to security functions and protected information is restricted to authorized personnel.

- id: ssp_nist80053r4_AC_17
  title: NIST 800-53r4 AC-17 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Technical Staff to the organization:

    a. Establishes and documents usage restrictions, configuration/connection requirements,
    and implementation guidance for each type of remote access allowed; and

    b. Authorizes remote access to the information system prior to allowing such connections.
    The Technical Staff are individuals with responsibility for managing the technical
    aspects of the information system.

- id: ssp_nist80053r4_IA_5
  title: NIST 800-53r4 IA-5 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Technical Staff to the organization manages information
    system authenticators by:

    a. Verifying, as part of the initial authenticator distribution, the identity
    of the individual, group, role, or device receiving the authenticator;

    b. Establishing initial authenticator content for authenticators defined by the
    organization;

    c. Ensuring that authenticators have sufficient strength of mechanism for their
    intended use;

    d. Establishing and implementing administrative procedures for initial authenticator
    distribution, for lost/compromised or damaged authenticators, and for revoking
    authenticators;

    e. Changing default content of authenticators prior to information system installation;

    f. Establishing minimum and maximum lifetime restrictions and reuse conditions
    for authenticators;

    g. Changing/refreshing authenticators [Assignment: organization-defined time period
    by authenticator type];

    h. Protecting authenticator content from unauthorized disclosure and modification;

    i. Requiring individuals to take, and having devices implement, specific security
    safeguards to protect authenticators; and

    j. Changing authenticators for group/role accounts when membership to those accounts
    changes. The Technical Staff are individuals with responsibility for managing
    the technical aspects of the information system.

- id: ssp_nist80053r4_IR_7
  title: NIST 800-53r4 IR-7 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Technical Staff to the organization provides an incident
    response support resource, integral to the organizational incident response capability
    that offers advice and assistance to users of the information system for the handling
    and reporting of security incidents. The Technical Staff are individuals with
    responsibility for managing the technical aspects of the information system.

- id: ssp_nist80053r4_MA_2
  title: NIST 800-53r4 MA-2 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Technical Staff to the organization:

    a. Schedules, performs, documents, and reviews records of maintenance and repairs
    on information system components in accordance with manufacturer or vendor specifications
    and/or organizational requirements;

    b. Approves and monitors all maintenance activities, whether performed on site
    or remotely and whether the equipment is serviced on site or removed to another
    location;

    c. Requires that [Assignment: organization-defined personnel or roles] explicitly
    approve the removal of the information system or system components from organizational
    facilities for off-site maintenance or repairs;

    d. Sanitizes equipment to remove all information from associated media prior to
    removal from organizational facilities for off-site maintenance or repairs;

    e. Checks all potentially impacted security controls to verify that the controls
    are still functioning properly following maintenance or repair actions; and

    f. Includes [Assignment: organization-defined maintenance-related information]
    in organizational maintenance records. The Technical Staff are individuals with
    responsibility for managing the technical aspects of the information system.

- id: ssp_nist80053r4_MA_4
  title: NIST 800-53r4 MA-4 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Technical Staff to the organization:

    a. Approves and monitors nonlocal maintenance and diagnostic activities;

    b. Allows the use of nonlocal maintenance and diagnostic tools only as consistent
    with organizational policy and documented in the security plan for the information
    system;

    c. Employs strong authenticators in the establishment of nonlocal maintenance
    and diagnostic sessions;

    d. Maintains records for nonlocal maintenance and diagnostic activities; and

    e. Terminates session and network connections when nonlocal maintenance is completed.
    The Technical Staff are individuals with responsibility for managing the technical
    aspects of the information system.

- id: ssp_nist80053r4_SI_2
  title: NIST 800-53r4 SI-2 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses Technical Staff to the organization:

    a. Identifies, reports, and corrects information system flaws;

    b. Tests software and firmware updates related to flaw remediation for effectiveness
    and potential side effects before installation;

    c. Installs security-relevant software and firmware updates within [Assignment:
    organization-defined time period] of the release of the updates; and

    d. Incorporates flaw remediation into the organizational configuration management
    process. The Technical Staff are individuals with responsibility for managing
    the technical aspects of the information system.

