id: app
title: TACR Change History
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-53-r4-ssp
- govready.com/apps/compliance/2017/tacr-ssp-text
- govready.com/apps/compliance/2017/change-history
version: 0.5
icon: app.png
catalog:
  category: Description
  vendor: ContractorCo
  vendor_url: http://www.ContractorCo.com
  status: draft
  version: 0.3
  source_url: https://github.com/GovReady/ssp-via-govready/tree/master/out/generic/change-history
  description:
    short: TACR Change History
    long: Generates the change history for TACR

introduction:
  format: markdown
  template: >-
    Generates the system description for TACR
questions:
- id: example
  title: Example Module
  type: module
  module-id: example

output:
- id: change_history
  title: TACR Change History
  format: markdown
  template: >+
    # TACR SSP Change History

    The current configuration of TACR instances has been in operation under SOD since FY2011. Prior to this, TACR was administered by the Center for Sobriety. The Department acknowledges that all future SOD sites will have to be added to the TACR as is; that each one’s security needs will be addressed individually as they are added to the TACR; and security documentation for each site will be added to this SSP as amendments or appendices as they are completed. 


    In September of 2016, the TACR systems were migrated from contractor owned and operated facility to the FedRAMP certified AWS cloud.


    October 2017: As the SSP is moving to Git, change history will be be maintained in the Git log.


    The SSP should be reviewed at least annually and necessary changes in controls or updates to the documentation should be recorded on the table below.

    <center>
    <table border="1" dir="auto"><tbody><tr><td><p>Version</p></td>
    <td><p>Release Date</p></td>
    <td><p>Summary of Changes</p></td>
    <td><p>Name</p></td>
    </tr><tr><td><p>1.0</p></td>
    <td><p>January 2008</p></td>
    <td><p>Initial Draft</p></td>
    <td><p>REDACTED</p></td>
    </tr><tr><td><p>1.1</p></td>
    <td><p>February 2008</p></td>
    <td><p>Section 1.0 &ndash; 2.0</p></td>
    <td><p>REDACTED</p></td>
    </tr><tr><td><p>1.1</p></td>
    <td><p>March 2008</p></td>
    <td><p>Section 2.0 - 3.0</p></td>
    <td><p>REDACTED</p></td>
    </tr><tr><td><p>1.1</p></td>
    <td><p>March 2008</p></td>
    <td><p>Section 3.1 &nbsp;-4.0</p></td>
    <td><p>REDACTED</p></td>
    </tr><tr><td><p>1.1</p></td>
    <td><p>April 2008</p></td>
    <td><p>Appendix A&amp;B</p></td>

    </table>

    CONTENT REDACTED

    <table border="1" dir="auto"><tbody><tr><td><p>Version</p></td>
    

    <tr><td><p>3.10</p></td>
    <td><p>January 2015</p></td>
    <td><p>Updated system list, and added &nbsp;Single Sign-On (SSO) information</p></td>
    <td><p>REDACTED</p></td>
    </tr>
    <tr><td><p>3.11</p></td>
    <td><p>November 2015</p></td>
    <td><p>Additional controls required for NIST SP800-53 Rev.4:</p><ul><li class="c1 c27">CA-9 added</li><li class="c1 c27">CM-10 added</li><li class="c1 c27">CM-11 added</li><li class="c1 c27">MA-1 added</li><li class="c1 c27">MP-7 added</li><li class="c1 c27">SI-4 added</li><li class="c1 c27">SC-39 added</li></ul><p>Updated system list</p><p>Removed Appendices for retired systems and mailman administration</p><p>Updated SOD contact information</p><p>Replaced remaining references to OVAE</p><p>Added appendices for the Sobrietist, Event Planner, and Wizard systems</p></td>
    <td><p>REDACTED</p></td>
    </tr>

    <tr><td>4.0</td><td>April 2017</td><td><p>System hosted on AWS FedRAMP-Certified data center</p><p>Migrated document to git</p><p>Updated system-identification and contacts</p></td><td>ContractorCo, Inc.</td></tr>
    <tr><td>4.1</td><td>September 2017</td><td>Updated to use new System, Technical templates</td><td>ContractorCo, Inc.</td></tr>
    <tr><td>4.2</td><td>October 2017</td><td><p>Updated information for ContractorCo Contract</p><p>Updated system diagrams</p><p>Generated by GovReady-Q with support from Git and OpenControl</p></td><td>ContractorCo, Inc.</td></tr>
    </tbody>
    </table>
    </center>
