id: app
title: New User Account Request form
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-53-r4-ssp
- govready.com/apps/compliance/2017/new-user-account-request-form
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: draft
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST 800-53r4) Compliance of New User Account Request form
    long: Generates compliance documentation of New User Account Request form as it
      pertains to managing the security of CUI (Controlled Unclassified Information)
      as per NIST 800-53r4 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    The New User Account Request Form is used by to initiate account access to a Department
    of Education information system.

    This application will make sure you are properly using New User Account Request
    form to protect CUI (Controlled Unclassified Information) as per NIST 800-53r4
    controls.
questions:
- id: example
  title: Example Module
  type: module
  module-id: example
output:
- id: ssp_nist80053r4_AC_2
  title: NIST 800-53r4 AC-2 Control Implementation
  format: markdown
  template: >+
    Access privileges are used to ensure that only authorized personnel access certain areas of the TACR System system. User access is controlled by the completion and submission of TACR System System Rules of Behavior and New User Account Request forms by the user and management.

    These items are completed and submitted whenever a new user requires access or an existing user requires access changes. The system administrator, based on need-to-know, assigns the proper permissions. The employee’s manager approves the access rights before the initial account is created by signing off on the forms. Finally, the system administrator implements the access rights according to the New User Account Request form. The security staff and the support contractor to determine recertification requirements review accounts periodically. Accounts no longer in use are removed from the system by the system administrator.

